<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FitHub.Business\FitHub.Business.csproj" />
    <ProjectReference Include="..\FitHub.Identity\FitHub.Identity.csproj" />
    <ProjectReference Include="..\FitHub.Infrastructure\FitHub.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Middlewares\" />
    <Folder Include="Extensions\" />
  </ItemGroup>

</Project>
